### ISSUE TITLE
`fev2tsv.py` output error

### ISSUE THREAD

**Issue by LanderDC** [rcedgar/palm_annot#3]
When converting the fev file to tsv format I encountered an issue when trying to use the `--output` option. This is a result of not opening the output file in write mode on line 61:
https://github.com/rcedgar/palm_annot/blob/15d9443b86b195f779dbf5a4255539f49caaec7c/py/fev2tsv.py#L61

I fixed this with following additions:
```python
fOut = sys.stdout
if not Args.output is None:
	fOut = open(Args.output, 'w')

# rest of code
...

if fOut is not sys.stdout:
	fOut.close()
# end of script
```

**Comment by rcedgar** [comment]
Fixed & committed, thanks for the report.

**Comment by LanderDC** [comment]
Thanks!
