### ISSUE TITLE
Error with `fasta_clean.py` in `palm_annot.py`. Add `RepoDir + "py/"`

### ISSUE THREAD

**Issue by LanderDC** [rcedgar/palm_annot#4]
Hi,

I had an error running `palm_annot.py`, because apparently  another `fasta_clean.py` was already installed globally on our server. I saw that in the `palm_annot.py` script you added `RepoDir + "py/"` to all the other python scripts except for `fasta_clean.py`.

https://github.com/rcedgar/palm_annot/blob/2b23ebee76eb100c848a14d3a569a64aee3b8361/py/palm_annot.py#L143

I fixed it on our server by adding this too (see below) and this would also make the `palm_annot.py` script more consistent:
```python
CmdLine = RepoDir + "py/fasta_clean.py"
```
Thanks!

**Comment by rcedgar** [comment]
Done, thanks for the catch!
